//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritoryGame.Log {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Logger : global::System.Configuration.ApplicationSettingsBase {
        
        private static Logger defaultInstance = ((Logger)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Logger())));
        
        public static Logger Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\TerritoryLog.txt")]
        public string LocalFile {
            get {
                return ((string)(this["LocalFile"]));
            }
            set {
                this["LocalFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogLocalFile {
            get {
                return ((bool)(this["LogLocalFile"]));
            }
            set {
                this["LogLocalFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogConsole {
            get {
                return ((bool)(this["LogConsole"]));
            }
            set {
                this["LogConsole"] = value;
            }
        }
    }
}
