//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritoryGame.Log {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerritoryGame.Log.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building {0} finished the production of {1}..
        /// </summary>
        internal static string BuildingProducedGameElement {
            get {
                return ResourceManager.GetString("BuildingProducedGameElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over..
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} won the game..
        /// </summary>
        internal static string GameWonBy {
            get {
                return ResourceManager.GetString("GameWonBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} attacked at {1} with the unit {2}..
        /// </summary>
        internal static string PlayerAttackedAt {
            get {
                return ResourceManager.GetString("PlayerAttackedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} created the building {1} with the unit {2}..
        /// </summary>
        internal static string PlayerCreatedBuilding {
            get {
                return ResourceManager.GetString("PlayerCreatedBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} was eliminated from the game..
        /// </summary>
        internal static string PlayerEliminated {
            get {
                return ResourceManager.GetString("PlayerEliminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} ended turn..
        /// </summary>
        internal static string PlayerEndedTurn {
            get {
                return ResourceManager.GetString("PlayerEndedTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} equipped unit {1} with the item {2}..
        /// </summary>
        internal static string PlayerEquippedUnitWith {
            get {
                return ResourceManager.GetString("PlayerEquippedUnitWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} influenced at {1} with the unit {2}..
        /// </summary>
        internal static string PlayerInfluencedAt {
            get {
                return ResourceManager.GetString("PlayerInfluencedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} moved the unit {1} to {2}..
        /// </summary>
        internal static string PlayerMovedUnitTo {
            get {
                return ResourceManager.GetString("PlayerMovedUnitTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} set production of {1} in the building {2}..
        /// </summary>
        internal static string PlayerSetProductionOf {
            get {
                return ResourceManager.GetString("PlayerSetProductionOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} lost its turn due to timeout..
        /// </summary>
        internal static string PlayerTurnTimeout {
            get {
                return ResourceManager.GetString("PlayerTurnTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit {0} attacked the unit {1} at {2}, damaged it by {3} and was damaged back by {4}..
        /// </summary>
        internal static string UnitAttackedAndDamaged {
            get {
                return ResourceManager.GetString("UnitAttackedAndDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit {0} destroyed the building {1} at {2}..
        /// </summary>
        internal static string UnitDestroyedBuilding {
            get {
                return ResourceManager.GetString("UnitDestroyedBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit {0} died in the battle..
        /// </summary>
        internal static string UnitDied {
            get {
                return ResourceManager.GetString("UnitDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit {0} influenced the territory at {1} by {2}..
        /// </summary>
        internal static string UnitInfluencedTerritory {
            get {
                return ResourceManager.GetString("UnitInfluencedTerritory", resourceCulture);
            }
        }
    }
}
